#!/bin/bash

#  This file is part of the program: Processor Modeling Tool (PMT).
#
#  PMT is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  PMT is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with PMT.  If not, see <http://www.gnu.org/licenses/>.
#
#  Authors: Sam Van den Steen, Ghent University
#  Copyright: 2016, Ghent University

PMT_DIR=$(dirname $(readlink -f "${BASH_SOURCE[0]}"))

if [ -z $AIP_ROOT ] ; then
	echo "AIP_ROOT not set, please specify the location:"
	read AIP_ROOT
fi

protoc -I=$AIP_ROOT/aif_lib/aif_proto --python_out=aif_lib/ $AIP_ROOT/aif_lib/aif_proto/branch_file.proto
protoc -I=$AIP_ROOT/aif_lib/aif_proto --python_out=aif_lib/ $AIP_ROOT/aif_lib/aif_proto/memory_file.proto
protoc -I=$AIP_ROOT/aif_lib/aif_proto --python_out=aif_lib/ $AIP_ROOT/aif_lib/aif_proto/mlp_file.proto
protoc -I=$AIP_ROOT/aif_lib/aif_proto --python_out=aif_lib/ $AIP_ROOT/aif_lib/aif_proto/cold_file.proto
protoc -I=$AIP_ROOT/aif_lib/aif_proto --python_out=aif_lib/ $AIP_ROOT/aif_lib/aif_proto/utrace_file.proto

protoc -I=aif_lib --python_out=aif_lib/ aif_lib/sd_hist_file.proto
